export const templates = [
  {
    id: 1,
    img_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTWPjwDrd8ZnaJWDqcNQCdAjQPgF58yRu-aD-M5ARWg1Jj8vuxr',
    free: true,
    price: 0,
    title: 'Mẫu giao diện số 1',
    like: 10,
    file_name: 'pink-flowers',
  },
  {
    id: 2,
    img_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRqJHctMVCCrtZhy3ChxtVjA5fPoqkTIu7QDPwIY89zdFpo-nu-',
    free: true,
    price: 0,
    title: 'Mẫu giao diện số 2',
    like: 5,
    file_name: 'goldern',
  },
  {
    id: 3,
    img_url: 'https://images.template.net/wp-content/uploads/2016/10/05065105/Wedding-Planning-Consultancy-WordPress-Website-Theme-75.jpg',
    free: true,
    price: 0,
    title: 'Mẫu giao diện số 3',
    like: 23,
  },
  {
    id: 4,
    img_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcR-sRllnhzLBC141yTYfn76_9Y56LtidIgpinukhMzXQ3XvsO2j',
    free: true,
    price: 0,
    title: 'Mẫu giao diện số 4',
    like: 43,
  },
  {
    id: 5,
    img_url: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQzAMrv7_f1MzY0zTMr4WQBa_-CsnE3VwfAOBdRaRgxCdVbSx-0',
    free: false,
    price: 100000,
    title: 'Mẫu giao diện số 5',
    like: 57,
  },
  {
    id: 6,
    img_url: 'https://cdn.colorlib.com/wp/wp-content/uploads/sites/2/invitation-html-wedding-website-template.jpg',
    free: false,
    price: 200000,
    title: 'Mẫu giao diện số 6',
    like: 100,
  },
];
